# Generated by Django 5.2.7 on 2026-01-17 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academic.semester",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("semester", "name")},
        ),
    ]
