# Generated by Django 5.2.7 on 2026-01-17 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine-generated"),
                            ("adhoc", "Ad-hoc (Extra class)"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration in minutes (for ad-hoc classes)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "is_holiday",
                    models.BooleanField(
                        default=False,
                        help_text="Mark if this is a holiday (manually marked)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "routine_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to routine entry if generated from routine",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="routine.routineentry",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academic.subject",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_record",
                "ordering": ["-date", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("subject", "date", "start_time"),
                        name="unique_attendance_record",
                    )
                ],
            },
        ),
    ]
